server:
  port: 8080
 
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/productdb
    username: root
    password: root

  jpa: 
    hibernate:
      ddl-auto: update 
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://localhost:9296

